# Site settings
name: Risma Rustiyan
description: "Information System Department, Faculty of Science and Technology, UIN SUSKA RIAU"
url: "https:sif.uin-suska.ac.id https:fst.uin-suska.ac.id, http://uin-suska.ac.id"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  rismarustiyan
facebook_username: "https://facebook.com"
twitter_username: "https://twitter.com"
google_plus_username: your_google_plus_username_goes_here
linkedin_username: "https://www.linkedin.com/in/risma-rustiyan-r-14021714b"
instagram_username:  "https://instagram.com"
blog_url: "/blog"
email: tianrustianrr@gmail.com
public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.png"
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "imgs/avatar.png"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/avatar.png"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
